//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.29 at 08:48:45 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mamarbari.com/testdemo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mamarbari.testdemo;
